apiVersion: v1
kind: Pod
metadata:
  name: event-pod 
  labels:
    app: eventssl
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: "4"
        nvidia.com/gpu: 1
      requests:
        memory: 30Gi
        cpu: "4"
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /eventssl-vol
      name: eventssl-vol
  volumes:
    - name: eventssl-vol
      persistentVolumeClaim:
        claimName: eventssl-vol 
