apiVersion: v1
kind: Pod
metadata:
  name: event-pod-cuda13
  labels:
    app: eventssl
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  containers:
  - name: container
    image: pytorch/pytorch:2.9.0-cuda13.0-cudnn9-devel
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: "4"
        nvidia.com/gpu: 1
      requests:
        memory: 30Gi
        cpu: "4"
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /eventssl-vol
      name: eventssl-vol
    - mountPath: /root/.ssh
      name: git-ssh
      readOnly: true
  volumes:
    - name: eventssl-vol
      persistentVolumeClaim:
        claimName: eventssl-vol 
    - name: git-ssh
      secret:
        secretName: git-ssh
        defaultMode: 0400
