apiVersion: batch/v1
kind: Job
metadata:
  labels:
    jobgroup: hhh-job-train
  name: ssl-calo-make-dataset
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    spec:
      containers:
      - name: training
        image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest 
        command:
        - "/bin/bash"
        - "-c"
        - >
          cd /eventssl-vol/particlemind &&
          pip install -e . &&
          pip install uproot --upgrade &&
          python /eventssl-vol/particlemind/data_processing/cld_root2parquet_parallel.py \
            --input_dir /eventssl-vol/particlemind/data/p8_ee_tt_ecm365/root \
            --output_dir /eventssl-vol/particlemind/data/p8_ee_tt_ecm365/parquet_full
        resources:
          limits:
            memory: 64Gi
            cpu: "10"
          requests:
            memory: 64Gi
            cpu: "10"
        volumeMounts:
        - mountPath: /eventssl-vol
          name: eventssl-vol
      volumes:
      - name: eventssl-vol
        persistentVolumeClaim:
          claimName: eventssl-vol
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - gpn-fiona-mizzou-2.rnet.missouri.edu
                  - gpengine-uams.areon.net
                  - rci-nrp-gpu-05.sdsu.edu
                  - node-2-2.sdsc.optiputer.net
                  - hcc-gpengine-shor-c5303.unl.edu
                  - node-1-3.sdsc.optiputer.net
                  - k8s-a100-01.suncorridor.org
                  - k8s-haosu-23.sdsc.optiputer.net
