apiVersion: batch/v1
kind: Job
metadata:
  labels:
    jobgroup: transformer-train
  name: ptv3-instance-10mm-train
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    spec:
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command:
        - "/bin/sh"
        - "-c"
        - >
          git clone --single-branch --branch master --recurse-submodules https://github.com/billy000400/spvnas.git /opt/repo/spvnas &&
          chown -R 1000:1000 /opt/repo/spvnas
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
      containers:
      - name: training
        image: gitlab-registry.nrp-nautilus.io/billy000400/pointtransformerv3:latest
        command:
        - "/bin/bash"
        - "-c"
        - >
          cd /eventssl-vol/PointTransformerV3 &&
          python train_instance.py --config configs/cld_10mm_tuned_loss.yaml
        resources:
          limits:
            memory: 32Gi
            cpu: "4"
            nvidia.com/gpu: "1"
          requests:
            memory: 32Gi
            cpu: "4"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - mountPath: /eventssl-vol
          name: eventssl-vol
      volumes:
        - name: eventssl-vol
          persistentVolumeClaim:
            claimName: eventssl-vol 
        - name: git-repo
          emptyDir: {}
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - gpn-fiona-mizzou-2.rnet.missouri.edu
                  - gpengine-uams.areon.net
                  - rci-nrp-gpu-05.sdsu.edu
                  - node-2-2.sdsc.optiputer.net
                  - hcc-gpengine-shor-c5303.unl.edu
                  - node-1-3.sdsc.optiputer.net
                  - k8s-a100-01.suncorridor.org
                  - k8s-haosu-23.sdsc.optiputer.net
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                # - NVIDIA-GeForce-GTX-1080
                # - NVIDIA-GeForce-GTX-1080-Ti
                # - NVIDIA-GeForce-GTX-2080-Ti
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-GeForce-RTX-4090
